"""Build the fixed MS-ILA Day-3 Overfit-16 architecture-QA dataset.

Scope
-----
This module implements ONLY Day-3 Task 7 (Overfit-16 dataset construction).
It does not implement loss, optimizer, trainer, visualization, checkpointing,
resume, integration QA, or Day-3 reporting.

Scientific purpose
------------------
Overfit-16 is a deliberately tiny, deterministic dataset used to answer one
engineering question:

    Can the current architecture memorize a controlled 16-sample problem?

It is NOT a benchmark set and MUST NOT be used to claim generalization,
AU-PRO_0.05 performance, or realism of synthetic defects.

Locked composition
------------------
- 16 distinct source images selected deterministically from a normal-only pool.
- 8 true normal samples (unchanged RGB image + all-zero mask).
- 8 controlled synthetic-anomaly samples generated by Task-6
  ``SyntheticAnomalyGenerator``.

The synthetic perturbation is applied BEFORE any Local/Context construction,
DINO normalization, DINOv3 extraction, feature cache, adapter, fusion, or
decoder stage. This prevents the invalid supervision case where a normal
feature tensor is paired with a synthetic anomaly mask that is not present in
the input image.

Output layout
-------------
<output_root>/
    manifest.json
    images/
        ov16_00_normal.png
        ...
        ov16_15_anomaly.png
    masks/
        ov16_00_normal.png
        ...
        ov16_15_anomaly.png

The manifest stores source provenance, deterministic seeds, exact output pixel
hashes, Task-6 metadata, and dataset-level descriptive statistics.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
import hashlib
import json
import os
from pathlib import Path
import shutil
import tempfile
from typing import Any, Iterable, Sequence

import numpy as np
import torch
from PIL import Image
from torch import Tensor

try:
    from src.data.synthetic_anomaly import (
        SyntheticAnomalyConfig,
        SyntheticAnomalyGenerator,
        summarize_synthetic_metadata,
    )
except ImportError:  # pragma: no cover - convenience for direct script execution
    from data.synthetic_anomaly import (  # type: ignore
        SyntheticAnomalyConfig,
        SyntheticAnomalyGenerator,
        summarize_synthetic_metadata,
    )


SCHEMA_NAME = "msila_overfit16"
SCHEMA_VERSION = 1
TOTAL_SAMPLES = 16
NORMAL_SAMPLES = 8
ANOMALY_SAMPLES = 8

IMAGE_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".tif",
    ".tiff",
    ".webp",
}


class Overfit16Error(RuntimeError):
    """Base class for Overfit-16 construction errors."""


class SourcePoolError(Overfit16Error):
    """Raised when the normal-image source pool is invalid."""


class ReproducibilityError(Overfit16Error):
    """Raised when a generated sample violates the locked dataset contract."""


def _sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _sha256_array(array: np.ndarray) -> str:
    arr = np.ascontiguousarray(array)
    h = hashlib.sha256()
    h.update(str(arr.dtype).encode("utf-8"))
    h.update(np.asarray(arr.shape, dtype=np.int64).tobytes())
    h.update(arr.tobytes())
    return h.hexdigest()


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def discover_normal_images(normal_root: str | Path) -> list[Path]:
    """Return a deterministic sorted list of candidate normal RGB images.

    The function assumes the caller points ``normal_root`` at a NORMAL-ONLY
    source directory (for example a category's normal training subset). It does
    not infer semantic labels from filenames.
    """
    root = Path(normal_root).expanduser().resolve()
    if not root.is_dir():
        raise SourcePoolError(f"normal_root is not a directory: {root}")

    files = [
        p
        for p in root.rglob("*")
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    ]
    files.sort(key=lambda p: p.relative_to(root).as_posix().casefold())

    if len(files) < TOTAL_SAMPLES:
        raise SourcePoolError(
            f"Overfit-16 requires at least {TOTAL_SAMPLES} distinct normal "
            f"source images, but only {len(files)} were found in {root}."
        )
    return files


def select_source_images(
    candidates: Sequence[Path],
    *,
    seed: int,
) -> list[Path]:
    """Select exactly 16 DISTINCT source images deterministically."""
    if len(candidates) < TOTAL_SAMPLES:
        raise SourcePoolError(
            f"Need >= {TOTAL_SAMPLES} candidates, got {len(candidates)}"
        )
    rng = np.random.Generator(np.random.PCG64(int(seed)))
    chosen_idx = rng.permutation(len(candidates))[:TOTAL_SAMPLES]
    selected = [candidates[int(i)] for i in chosen_idx]
    if len({p.resolve() for p in selected}) != TOTAL_SAMPLES:
        raise ReproducibilityError("Source selection contains duplicate files")
    return selected


def _load_rgb_tensor(path: Path) -> tuple[Tensor, np.ndarray]:
    """Decode one image as RGB uint8 and float32 CHW in [0,1]."""
    with Image.open(path) as im:
        rgb = np.asarray(im.convert("RGB"), dtype=np.uint8).copy()

    if rgb.ndim != 3 or rgb.shape[2] != 3:
        raise SourcePoolError(f"Could not decode RGB image: {path}")
    if rgb.shape[0] < 2 or rgb.shape[1] < 2:
        raise SourcePoolError(f"Image is too small: {path} -> {rgb.shape}")

    tensor = torch.from_numpy(rgb).permute(2, 0, 1).float().div_(255.0)
    return tensor.contiguous(), rgb


def _tensor_rgb_to_uint8(image: Tensor) -> np.ndarray:
    if image.ndim != 3 or image.shape[0] != 3:
        raise ReproducibilityError(
            f"Expected RGB tensor [3,H,W], got {tuple(image.shape)}"
        )
    if not image.is_floating_point() or not torch.isfinite(image).all().item():
        raise ReproducibilityError("Generated image must be finite floating point")

    x = image.detach().cpu().clamp(0.0, 1.0)
    array = (
        x.permute(1, 2, 0)
        .mul(255.0)
        .round()
        .to(torch.uint8)
        .numpy()
    )
    return np.ascontiguousarray(array)


def _mask_to_uint8(mask: Tensor) -> np.ndarray:
    if mask.ndim != 3 or mask.shape[0] != 1:
        raise ReproducibilityError(
            f"Expected binary mask [1,H,W], got {tuple(mask.shape)}"
        )
    if not torch.isfinite(mask).all().item():
        raise ReproducibilityError("Mask contains NaN/Inf")

    unique = set(float(v) for v in torch.unique(mask.detach().cpu()))
    if not unique.issubset({0.0, 1.0}):
        raise ReproducibilityError(f"Mask is not binary: values={sorted(unique)}")

    return (
        mask[0].detach().cpu().gt(0.5).to(torch.uint8).mul(255).numpy()
    ).copy()


def _save_png_rgb(path: Path, array: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(array, mode="RGB").save(path, format="PNG")


def _save_png_mask(path: Path, array: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(array, mode="L").save(path, format="PNG")


def _load_png_rgb(path: Path) -> np.ndarray:
    with Image.open(path) as im:
        return np.asarray(im.convert("RGB"), dtype=np.uint8).copy()


def _load_png_mask(path: Path) -> np.ndarray:
    with Image.open(path) as im:
        return np.asarray(im.convert("L"), dtype=np.uint8).copy()


def _validate_saved_pair(
    *,
    source_rgb: np.ndarray,
    output_rgb: np.ndarray,
    output_mask: np.ndarray,
    is_anomaly: bool,
) -> None:
    """Validate the exact persisted image-mask contract after PNG round-trip."""
    if output_rgb.shape != source_rgb.shape:
        raise ReproducibilityError(
            f"Saved RGB shape changed: source={source_rgb.shape}, output={output_rgb.shape}"
        )
    if output_mask.shape != source_rgb.shape[:2]:
        raise ReproducibilityError(
            "Saved mask shape does not match image: "
            f"mask={output_mask.shape}, image={source_rgb.shape[:2]}"
        )

    unique = set(int(v) for v in np.unique(output_mask))
    if not unique.issubset({0, 255}):
        raise ReproducibilityError(f"Persisted mask is not binary: {sorted(unique)}")

    mask_bool = output_mask > 0

    if is_anomaly:
        if not mask_bool.any():
            raise ReproducibilityError("Synthetic anomaly sample has an empty saved mask")

        # Quantization-safe synchronization gate: source pixels outside the
        # exact mask must be byte-identical after standard PNG serialization.
        outside = ~mask_bool
        if not np.array_equal(output_rgb[outside], source_rgb[outside]):
            raise ReproducibilityError(
                "Saved synthetic image changed pixels outside the GT mask"
            )

        # Require a visible persisted change somewhere inside the mask.
        if np.array_equal(output_rgb[mask_bool], source_rgb[mask_bool]):
            raise ReproducibilityError(
                "Saved anomaly image has no RGB change inside the GT mask"
            )
    else:
        if mask_bool.any():
            raise ReproducibilityError("Normal sample must have an all-zero mask")
        if not np.array_equal(output_rgb, source_rgb):
            raise ReproducibilityError(
                "Normal Overfit-16 sample must be pixel-identical to decoded source"
            )


def _generator_signature(generator: SyntheticAnomalyGenerator) -> dict[str, Any]:
    config = getattr(generator, "config", None)
    if isinstance(config, SyntheticAnomalyConfig):
        return {
            "class": type(generator).__name__,
            "config": asdict(config),
        }
    return {"class": type(generator).__name__}


def _json_dump_atomic(path: Path, payload: dict[str, Any]) -> None:
    tmp = path.with_name(path.name + f".tmp.{os.getpid()}")
    try:
        with tmp.open("w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2, sort_keys=True)
            f.write("\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def build_overfit16(
    normal_root: str | Path,
    output_root: str | Path,
    *,
    base_seed: int = 2026,
    selection_seed: int | None = None,
    generator: SyntheticAnomalyGenerator | None = None,
    category: str | None = None,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Build the locked 8-normal + 8-synthetic Overfit-16 dataset.

    Reproducibility contract
    ------------------------
    For the same:
      - source normal-image pool and file contents,
      - ``base_seed`` / ``selection_seed``,
      - Task-6 generator implementation + config,

    this function selects the same 16 source files and produces identical RGB
    and mask pixel arrays.

    Parameters
    ----------
    normal_root:
        Directory containing only NORMAL source images. Search is recursive.
    output_root:
        Destination directory. It must not be inside ``normal_root`` because
        generated PNGs would contaminate later source discovery.
    base_seed:
        Seed schedule for per-sample Task-6 generation: ``base_seed + index``.
    selection_seed:
        Seed for selecting 16 distinct sources. Defaults to ``base_seed``.
    generator:
        Optional preconfigured Task-6 generator. Defaults to
        ``SyntheticAnomalyGenerator()``.
    category:
        Optional category label stored in the manifest only.
    overwrite:
        Replace an existing output directory when True.
    """
    normal_root = Path(normal_root).expanduser().resolve()
    output_root = Path(output_root).expanduser().resolve()

    if output_root == normal_root or _is_relative_to(output_root, normal_root):
        raise Overfit16Error(
            "output_root must not be inside normal_root; otherwise generated "
            "files would contaminate deterministic source discovery."
        )

    if output_root.exists() and not overwrite:
        raise FileExistsError(
            f"Output already exists: {output_root}. Use overwrite=True explicitly."
        )

    if selection_seed is None:
        selection_seed = int(base_seed)

    generator = generator or SyntheticAnomalyGenerator()

    candidates = discover_normal_images(normal_root)
    selected = select_source_images(candidates, seed=int(selection_seed))

    # Build in a temporary sibling directory, then atomically rename where the
    # platform permits. This avoids leaving a half-built QA dataset.
    output_root.parent.mkdir(parents=True, exist_ok=True)
    tmp_root = Path(
        tempfile.mkdtemp(
            prefix=output_root.name + ".tmp.",
            dir=str(output_root.parent),
        )
    )

    records: list[dict[str, Any]] = []
    synth_metadata: list[dict[str, Any]] = []

    try:
        images_dir = tmp_root / "images"
        masks_dir = tmp_root / "masks"
        images_dir.mkdir(parents=True, exist_ok=True)
        masks_dir.mkdir(parents=True, exist_ok=True)

        for index, source_path in enumerate(selected):
            is_anomaly = index >= NORMAL_SAMPLES
            kind = "anomaly" if is_anomaly else "normal"
            sample_id = f"ov16_{index:02d}_{kind}"
            sample_seed = int(base_seed) + index

            source_tensor, source_rgb = _load_rgb_tensor(source_path)

            generated = generator(
                source_tensor,
                seed=sample_seed,
                force_anomaly=is_anomaly,
            )

            if bool(generated.metadata.get("is_anomaly")) != is_anomaly:
                raise ReproducibilityError(
                    f"Task-6 label mismatch for {sample_id}: "
                    f"expected is_anomaly={is_anomaly}"
                )

            out_rgb = _tensor_rgb_to_uint8(generated.image)
            out_mask = _mask_to_uint8(generated.mask)

            image_rel = Path("images") / f"{sample_id}.png"
            mask_rel = Path("masks") / f"{sample_id}.png"
            image_path = tmp_root / image_rel
            mask_path = tmp_root / mask_rel

            _save_png_rgb(image_path, out_rgb)
            _save_png_mask(mask_path, out_mask)

            # Validate exact persisted pixels, not only in-memory tensors.
            persisted_rgb = _load_png_rgb(image_path)
            persisted_mask = _load_png_mask(mask_path)
            _validate_saved_pair(
                source_rgb=source_rgb,
                output_rgb=persisted_rgb,
                output_mask=persisted_mask,
                is_anomaly=is_anomaly,
            )

            source_rel = source_path.relative_to(normal_root).as_posix()
            record = {
                "index": index,
                "sample_id": sample_id,
                "split": "overfit16",
                "purpose": "architecture_qa_only",
                "category": category,
                "is_anomaly": is_anomaly,
                "label": int(is_anomaly),
                "seed": sample_seed,
                "source_relpath": source_rel,
                "source_sha256": _sha256_file(source_path),
                "image_path": image_rel.as_posix(),
                "mask_path": mask_rel.as_posix(),
                "image_hw": [int(persisted_rgb.shape[0]), int(persisted_rgb.shape[1])],
                "image_pixel_sha256": _sha256_array(persisted_rgb),
                "mask_pixel_sha256": _sha256_array(persisted_mask),
                "synthetic": generated.metadata,
            }
            records.append(record)
            synth_metadata.append(generated.metadata)

        # Hard composition gates.
        if len(records) != TOTAL_SAMPLES:
            raise ReproducibilityError(
                f"Expected {TOTAL_SAMPLES} records, got {len(records)}"
            )
        if sum(not r["is_anomaly"] for r in records) != NORMAL_SAMPLES:
            raise ReproducibilityError("Overfit-16 must contain exactly 8 normal samples")
        if sum(r["is_anomaly"] for r in records) != ANOMALY_SAMPLES:
            raise ReproducibilityError("Overfit-16 must contain exactly 8 anomaly samples")
        if len({r["source_relpath"] for r in records}) != TOTAL_SAMPLES:
            raise ReproducibilityError("Overfit-16 source files must be distinct")
        if len({r["sample_id"] for r in records}) != TOTAL_SAMPLES:
            raise ReproducibilityError("Overfit-16 sample IDs must be unique")

        manifest: dict[str, Any] = {
            "schema_name": SCHEMA_NAME,
            "schema_version": SCHEMA_VERSION,
            "purpose": "architecture_qa_only",
            "benchmark_use_allowed": False,
            "realism_claim_allowed": False,
            "composition": {
                "total": TOTAL_SAMPLES,
                "normal": NORMAL_SAMPLES,
                "synthetic_anomaly": ANOMALY_SAMPLES,
            },
            "seeds": {
                "base_seed": int(base_seed),
                "selection_seed": int(selection_seed),
                "sample_seed_rule": "base_seed + index",
            },
            "source": {
                "normal_root_name": normal_root.name,
                "candidate_count": len(candidates),
                "selection_rule": "seeded_permutation_without_replacement",
                "assumption": "normal_root contains only normal images",
            },
            "synthetic_generator": _generator_signature(generator),
            "descriptive_summary": summarize_synthetic_metadata(synth_metadata),
            "samples": records,
        }

        _json_dump_atomic(tmp_root / "manifest.json", manifest)

        if output_root.exists():
            if not overwrite:
                raise FileExistsError(output_root)
            shutil.rmtree(output_root)

        os.replace(tmp_root, output_root)
        return manifest

    except Exception:
        shutil.rmtree(tmp_root, ignore_errors=True)
        raise


def verify_overfit16(output_root: str | Path) -> dict[str, Any]:
    """Verify a built Overfit-16 directory without regenerating it."""
    root = Path(output_root).expanduser().resolve()
    manifest_path = root / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(manifest_path)

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_name") != SCHEMA_NAME:
        raise ReproducibilityError(
            f"Unexpected schema_name={manifest.get('schema_name')!r}"
        )
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ReproducibilityError(
            f"Unexpected schema_version={manifest.get('schema_version')!r}"
        )

    records = manifest.get("samples")
    if not isinstance(records, list) or len(records) != TOTAL_SAMPLES:
        raise ReproducibilityError("Manifest must contain exactly 16 samples")

    normal_count = 0
    anomaly_count = 0
    source_names: set[str] = set()
    sample_ids: set[str] = set()

    for record in records:
        image_path = root / record["image_path"]
        mask_path = root / record["mask_path"]
        if not image_path.is_file() or not mask_path.is_file():
            raise ReproducibilityError(
                f"Missing persisted pair for sample_id={record.get('sample_id')}"
            )

        image = _load_png_rgb(image_path)
        mask = _load_png_mask(mask_path)
        if _sha256_array(image) != record["image_pixel_sha256"]:
            raise ReproducibilityError(
                f"Image pixel hash mismatch: {record['sample_id']}"
            )
        if _sha256_array(mask) != record["mask_pixel_sha256"]:
            raise ReproducibilityError(
                f"Mask pixel hash mismatch: {record['sample_id']}"
            )
        if image.shape[:2] != mask.shape:
            raise ReproducibilityError(
                f"Image/mask H,W mismatch: {record['sample_id']}"
            )
        if not set(int(v) for v in np.unique(mask)).issubset({0, 255}):
            raise ReproducibilityError(
                f"Non-binary saved mask: {record['sample_id']}"
            )

        is_anomaly = bool(record["is_anomaly"])
        if is_anomaly:
            anomaly_count += 1
            if not (mask > 0).any():
                raise ReproducibilityError(
                    f"Anomaly mask is empty: {record['sample_id']}"
                )
        else:
            normal_count += 1
            if (mask > 0).any():
                raise ReproducibilityError(
                    f"Normal mask is nonzero: {record['sample_id']}"
                )

        source_names.add(str(record["source_relpath"]))
        sample_ids.add(str(record["sample_id"]))

    if normal_count != NORMAL_SAMPLES or anomaly_count != ANOMALY_SAMPLES:
        raise ReproducibilityError(
            f"Expected 8 normal + 8 anomaly, got {normal_count} + {anomaly_count}"
        )
    if len(source_names) != TOTAL_SAMPLES or len(sample_ids) != TOTAL_SAMPLES:
        raise ReproducibilityError("Source paths and sample IDs must be unique")

    return {
        "status": "PASS",
        "schema_name": SCHEMA_NAME,
        "schema_version": SCHEMA_VERSION,
        "n_samples": TOTAL_SAMPLES,
        "n_normal": NORMAL_SAMPLES,
        "n_anomaly": ANOMALY_SAMPLES,
    }


def _main() -> None:
    parser = argparse.ArgumentParser(
        description="Build deterministic MS-ILA Day-3 Overfit-16 dataset."
    )
    parser.add_argument(
        "--normal-root",
        default=None,
        help="Directory containing NORMAL source images only (recursive scan).",
    )
    parser.add_argument("--output-root", required=True)
    parser.add_argument("--base-seed", type=int, default=2026)
    parser.add_argument("--selection-seed", type=int, default=None)
    parser.add_argument("--category", default=None)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Verify an already-built output-root; ignore normal-root/build args.",
    )
    args = parser.parse_args()

    if args.verify_only:
        report = verify_overfit16(args.output_root)
    else:
        if args.normal_root is None:
            parser.error("--normal-root is required unless --verify-only is used")
        manifest = build_overfit16(
            normal_root=args.normal_root,
            output_root=args.output_root,
            base_seed=args.base_seed,
            selection_seed=args.selection_seed,
            category=args.category,
            overwrite=args.overwrite,
        )
        report = {
            "status": "BUILT",
            "output_root": str(Path(args.output_root).expanduser()),
            "n_samples": len(manifest["samples"]),
            "composition": manifest["composition"],
            "descriptive_summary": manifest["descriptive_summary"],
        }

    print(json.dumps(report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    _main()


__all__ = [
    "SCHEMA_NAME",
    "SCHEMA_VERSION",
    "TOTAL_SAMPLES",
    "NORMAL_SAMPLES",
    "ANOMALY_SAMPLES",
    "Overfit16Error",
    "SourcePoolError",
    "ReproducibilityError",
    "discover_normal_images",
    "select_source_images",
    "build_overfit16",
    "verify_overfit16",
]
